name: webian
description: A new Flutter package.
version: 2.0.0

environment:
    sdk: ">=2.16.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    rxdart: ^0.27.3

    flutter_riverpod: ^1.0.3

    equatable: 2.0.3

    dart_extras:
        git:
            url: https://github.com/webian-dart/dart_extras.git

dev_dependencies:
    flutter_test:
        sdk: flutter

    test: any

    mocktail: 0.2.0

    fake_async: 1.2.0

    clock: 1.1.0

#dependency_overrides:
#    dart_extras:
#        path: ../dart_extras
